version: '3'
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'

  muffet:
    depends_on:
      - app
    image: raviqqe/muffet

  curl:
    depends_on:
      - app
    image: curlimages/curl:latest

